let grocery = [];
grocery.push ("Milk","Eggs","Bread")
grocery.pop(2)
grocery.unshift("Fruits")
grocery.shift(0)
console.log(grocery);


//studennt enrollment system

let enrollment = ["John","Emma","Noah","Liam"]
enrollment.pop(3)
enrollment.splice(2)
enrollment.push("Sophia")
console.log(enrollment);


// Movie Playlist editor
 var movies = ["Inception", "Avatar", "Titanic", "Joker", "Interstellar"]
  movies.splice(3,1,"the Matrix");

 console.log(movies);

console.log(movies)

let hi = ["apple","banana","Strawberry"]
hi.push("guava")
hi.shift()
hi.splice(1,0,"Mango")
hi.splice(1,0,"")
console.log(hi);
//
let student = ["Alice", "Bob", "Charlie"]
student.push("David")
student.unshift("Emma")
student.shift()
console.log(student)
